OLED_ENABLE = yes
OLED_DRIVER = SSD1306   # Enables the use of OLED displays
ENCODER_ENABLE = no       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
TAP_DANCE_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
RGB_MATRIX_ENABLE = no
OLED_DISABLE_TIMEOUT = yes
